name: CI

on:
  push:
    tags:
      - admin-web

  workflow_dispatch:

jobs:
  job_install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out current commit (${{ github.sha }})
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1

      - name: npm cache
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: yarn
    outputs:
      dependency_cache_key: ${{ steps.cache.outputs.hash }}

  job_build:
    name: build
    needs: job_install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: build admin-web
        run: cd admin-web && yarn build
